# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfda7e35e5cba51d378dd40b92842bdc6580e3776ff6ec371bf1fdcb2f504e40a1c094fe6678766e3f48298a5e95dd20885985e2c7ac5543832226dc79d334b0

test:
  secret_key_base: 841de7e862e1700dc645516a47a57075847effec275cddbadce79968c0f60d2e07fb11813b98c40665406d925a46c71bc8b2eedb7f8ca88d832957436f7b8d30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
